# Generated by Django 4.1.7 on 2023-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(max_length=4000)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
